services:
    web:
        build: ./
        command: yarn dev
        container_name: express
        volumes:
            - ./:/app/
            - /app/node_modules
        ports:
            - 3000:3000

    db:
        image: postgres:16.2
        container_name: postgres
        environment:
            POSTGRES_DB: 'newPostgres'
            POSTGRES_USER: 'username'
            POSTGRES_PASSWORD: 'password'
        ports:
            - '5432:5432'
